name: Backup config to s3

on:
  push:
    branches:
    - master

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: backup-dir
    - name: run a one-line script
      run: echo Hello, world!
    - name: ls current directory
      run: ls
    - name: cd to backup-dir
      run: cd backup-dir && ls
    - name: ls inside backup-dir
      run: ls
