name: Backup config to s3

on:
  push:
    branches:
    - master

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: backup-dir
    - name: zip backup-dir
      run: zip -r backup.zip ./backup-dir
    - name: list directory to check for zip
      run: ls
