name: Backup config to s3

on:
  push:
    branches:
    - master

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: backup-dir
    - name: look at root
      run: cd / && ls
    - name: look at github dir
      run: cd /github && ls
    - name: zip backup-dir
      run: zip -r backup.zip ./backup-dir -x "./backup-dir/.git/*" "./backup-dir/.github/*"
    - name: display github/workspace
      run: cd /github/workspace && ls && pwd
    - name: see where we are after the previous cd command
      run: ls && pwd
    - name: zip backup-dir to github/workspace
      run: zip -r /github/workspace/backup.zip ./backup-dir -x "./backup-dir/.git/*" "./backup-dir/.github/*"
    - name: display stuff
      run: ls && pwd
    - name: display github/workspace2
      run: cd /github/workspace && ls && pwd
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'backup.zip'
        DEST_DIR: '/'
